export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_USER_ROOMS_SUCCESS = 'FETCH_USER_ROOMS_SUCCESS';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const ROOM_JOINED = 'ROOM_JOINED';
